
package com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HCMDataLoader", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/", wsdlLocation = "https://edvn-test.fa.us2.oraclecloud.com/hcmCommonDataLoader/HCMDataLoader?wsdl")
public class HCMDataLoader_Service
    extends Service
{

    private final static URL HCMDATALOADER_WSDL_LOCATION;
    private final static WebServiceException HCMDATALOADER_EXCEPTION;
    private final static QName HCMDATALOADER_QNAME = new QName("http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/", "HCMDataLoader");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://edvn-test.fa.us2.oraclecloud.com/hcmCommonDataLoader/HCMDataLoader?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HCMDATALOADER_WSDL_LOCATION = url;
        HCMDATALOADER_EXCEPTION = e;
    }

    public HCMDataLoader_Service() {
        super(__getWsdlLocation(), HCMDATALOADER_QNAME);
    }

    public HCMDataLoader_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HCMDATALOADER_QNAME, features);
    }

    public HCMDataLoader_Service(URL wsdlLocation) {
        super(wsdlLocation, HCMDATALOADER_QNAME);
    }

    public HCMDataLoader_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HCMDATALOADER_QNAME, features);
    }

    public HCMDataLoader_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HCMDataLoader_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HCMDataLoader
     */
    @WebEndpoint(name = "HCMDataLoaderSoapHttpPort")
    public HCMDataLoader getHCMDataLoaderSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/", "HCMDataLoaderSoapHttpPort"), HCMDataLoader.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HCMDataLoader
     */
    @WebEndpoint(name = "HCMDataLoaderSoapHttpPort")
    public HCMDataLoader getHCMDataLoaderSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/", "HCMDataLoaderSoapHttpPort"), HCMDataLoader.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HCMDATALOADER_EXCEPTION!= null) {
            throw HCMDATALOADER_EXCEPTION;
        }
        return HCMDATALOADER_WSDL_LOCATION;
    }

}
