
package com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HCMDataLoader", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface HCMDataLoader {


    /**
     * 
     * @param contentId
     * @param parameters
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/importAndLoadData")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
    @RequestWrapper(localName = "importAndLoadData", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ImportAndLoadData")
    @ResponseWrapper(localName = "importAndLoadDataResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ImportAndLoadDataResponse")
    public String importAndLoadData(
        @WebParam(name = "ContentId", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String contentId,
        @WebParam(name = "Parameters", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String parameters)
        throws ServiceException
    ;

    /**
     * 
     * @param contentId
     * @param parameters
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/importAndLoadDataAsync")
    @Oneway
    @RequestWrapper(localName = "importAndLoadDataAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ImportAndLoadDataAsync")
    public void importAndLoadDataAsync(
        @WebParam(name = "ContentId", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String contentId,
        @WebParam(name = "Parameters", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String parameters);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDataSetStatus")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
    @RequestWrapper(localName = "getDataSetStatus", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDataSetStatus")
    @ResponseWrapper(localName = "getDataSetStatusResponse", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDataSetStatusResponse")
    public String getDataSetStatus(
        @WebParam(name = "Parameters", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String parameters)
        throws ServiceException
    ;

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDataSetStatusAsync")
    @Oneway
    @RequestWrapper(localName = "getDataSetStatusAsync", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/", className = "com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDataSetStatusAsync")
    public void getDataSetStatusAsync(
        @WebParam(name = "Parameters", targetNamespace = "http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/")
        String parameters);

}
