
package com.oracle.xmlns.oxp.service.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScheduleService", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScheduleService {


    /**
     * 
     * @param password
     * @param jobOutputID
     * @param userID
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getDocumentDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getDocumentData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDocumentData")
    @ResponseWrapper(localName = "getDocumentDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDocumentDataResponse")
    public byte[] getDocumentData(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param submittedJobId
     * @param password
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.ArrayOfString
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getAllJobInstanceIDsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getAllJobInstanceIDs", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllJobInstanceIDs")
    @ResponseWrapper(localName = "getAllJobInstanceIDsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllJobInstanceIDsResponse")
    public ArrayOfString getAllJobInstanceIDs(
        @WebParam(name = "submittedJobId", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String submittedJobId,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param filter
     * @param beginIdx
     * @param password
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobInfosList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getAllScheduledReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getAllScheduledReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReport")
    @ResponseWrapper(localName = "getAllScheduledReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportResponse")
    public JobInfosList getAllScheduledReport(
        @WebParam(name = "filter", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        JobFilterProperties filter,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param filter
     * @param beginIdx
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobInfosList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getAllScheduledReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getAllScheduledReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportInSession")
    @ResponseWrapper(localName = "getAllScheduledReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportInSessionResponse")
    public JobInfosList getAllScheduledReportInSession(
        @WebParam(name = "filter", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        JobFilterProperties filter,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobDetail
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledJobInfoReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledJobInfo", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledJobInfo")
    @ResponseWrapper(localName = "getScheduledJobInfoResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledJobInfoResponse")
    public JobDetail getScheduledJobInfo(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobDetail
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledJobInfoInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledJobInfoInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledJobInfoInSession")
    @ResponseWrapper(localName = "getScheduledJobInfoInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledJobInfoInSessionResponse")
    public JobDetail getScheduledJobInfoInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param scheduledJobID
     * @param password
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobStatus
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportStatusReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportStatus", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportStatus")
    @ResponseWrapper(localName = "getScheduledReportStatusResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportStatusResponse")
    public JobStatus getScheduledReportStatus(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param scheduledJobID
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobStatus
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportStatusInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportStatusInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportStatusInSession")
    @ResponseWrapper(localName = "getScheduledReportStatusInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportStatusInSessionResponse")
    public JobStatus getScheduledReportStatusInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param filter
     * @param beginIdx
     * @param password
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobInfosList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getAllScheduledReportHistoryReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getAllScheduledReportHistory", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportHistory")
    @ResponseWrapper(localName = "getAllScheduledReportHistoryResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportHistoryResponse")
    public JobInfosList getAllScheduledReportHistory(
        @WebParam(name = "filter", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        JobFilterProperties filter,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param filter
     * @param beginIdx
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobInfosList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getAllScheduledReportHistoryInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getAllScheduledReportHistoryInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportHistoryInSession")
    @ResponseWrapper(localName = "getAllScheduledReportHistoryInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetAllScheduledReportHistoryInSessionResponse")
    public JobInfosList getAllScheduledReportHistoryInSession(
        @WebParam(name = "filter", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        JobFilterProperties filter,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobOutputsList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportOutputInfoReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportOutputInfo", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportOutputInfo")
    @ResponseWrapper(localName = "getScheduledReportOutputInfoResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportOutputInfoResponse")
    public JobOutputsList getScheduledReportOutputInfo(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobOutputsList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportOutputInfoInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportOutputInfoInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportOutputInfoInSession")
    @ResponseWrapper(localName = "getScheduledReportOutputInfoInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportOutputInfoInSessionResponse")
    public JobOutputsList getScheduledReportOutputInfoInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobOutputID
     * @param bipSessionToken
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getDocumentDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getDocumentDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDocumentDataInSession")
    @ResponseWrapper(localName = "getDocumentDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDocumentDataInSessionResponse")
    public byte[] getDocumentDataInSession(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobOutputID
     * @param userID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadDocumentDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadDocumentData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadDocumentData")
    @ResponseWrapper(localName = "downloadDocumentDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadDocumentDataResponse")
    public String downloadDocumentData(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobOutputID
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadDocumentDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadDocumentDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadDocumentDataInSession")
    @ResponseWrapper(localName = "downloadDocumentDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadDocumentDataInSessionResponse")
    public String downloadDocumentDataInSession(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getXMLDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXMLData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetXMLData")
    @ResponseWrapper(localName = "getXMLDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetXMLDataResponse")
    public byte[] getXMLData(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getXMLDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXMLDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetXMLDataInSession")
    @ResponseWrapper(localName = "getXMLDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetXMLDataInSessionResponse")
    public byte[] getXMLDataInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadXMLDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadXMLData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadXMLData")
    @ResponseWrapper(localName = "downloadXMLDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadXMLDataResponse")
    public String downloadXMLData(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadXMLDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadXMLDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadXMLDataInSession")
    @ResponseWrapper(localName = "downloadXMLDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DownloadXMLDataInSessionResponse")
    public String downloadXMLDataInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param outputJobID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "resendScheduledReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "resendScheduledReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResendScheduledReport")
    @ResponseWrapper(localName = "resendScheduledReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResendScheduledReportResponse")
    public boolean resendScheduledReport(
        @WebParam(name = "outputJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String outputJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param outputJobID
     * @param bipSessionToken
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "resendScheduledReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "resendScheduledReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResendScheduledReportInSession")
    @ResponseWrapper(localName = "resendScheduledReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResendScheduledReportInSessionResponse")
    public boolean resendScheduledReportInSession(
        @WebParam(name = "outputJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String outputJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param instanceJobID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteJobHistoryReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deleteJobHistory", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteJobHistory")
    @ResponseWrapper(localName = "deleteJobHistoryResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteJobHistoryResponse")
    public boolean deleteJobHistory(
        @WebParam(name = "instanceJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String instanceJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param instanceJobID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteJobHistoryInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deleteJobHistoryInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteJobHistoryInSession")
    @ResponseWrapper(localName = "deleteJobHistoryInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteJobHistoryInSessionResponse")
    public boolean deleteJobHistoryInSession(
        @WebParam(name = "instanceJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String instanceJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param instanceJobID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "purgeJobHistoryReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "purgeJobHistory", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.PurgeJobHistory")
    @ResponseWrapper(localName = "purgeJobHistoryResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.PurgeJobHistoryResponse")
    public boolean purgeJobHistory(
        @WebParam(name = "instanceJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String instanceJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param instanceJobID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "purgeJobHistoryInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "purgeJobHistoryInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.PurgeJobHistoryInSession")
    @ResponseWrapper(localName = "purgeJobHistoryInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.PurgeJobHistoryInSessionResponse")
    public boolean purgeJobHistoryInSession(
        @WebParam(name = "instanceJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String instanceJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobOutputID
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobOutputDeliverysList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportDeliveryInfoReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportDeliveryInfo", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportDeliveryInfo")
    @ResponseWrapper(localName = "getScheduledReportDeliveryInfoResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportDeliveryInfoResponse")
    public JobOutputDeliverysList getScheduledReportDeliveryInfo(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobOutputID
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.JobOutputDeliverysList
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportDeliveryInfoInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getScheduledReportDeliveryInfoInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportDeliveryInfoInSession")
    @ResponseWrapper(localName = "getScheduledReportDeliveryInfoInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetScheduledReportDeliveryInfoInSessionResponse")
    public JobOutputDeliverysList getScheduledReportDeliveryInfoInSession(
        @WebParam(name = "jobOutputID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobOutputID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param scheduleRequest
     * @param password
     * @param userID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "scheduleReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "scheduleReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ScheduleReport")
    @ResponseWrapper(localName = "scheduleReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ScheduleReportResponse")
    public String scheduleReport(
        @WebParam(name = "scheduleRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ScheduleRequest scheduleRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param scheduleRequest
     * @param deliveryChannels
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "scheduleReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "scheduleReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ScheduleReportInSession")
    @ResponseWrapper(localName = "scheduleReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ScheduleReportInSessionResponse")
    public String scheduleReportInSession(
        @WebParam(name = "scheduleRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ScheduleRequest scheduleRequest,
        @WebParam(name = "deliveryChannels", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        DeliveryChannels deliveryChannels,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduleReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deleteSchedule", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteSchedule")
    @ResponseWrapper(localName = "deleteScheduleResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteScheduleResponse")
    public boolean deleteSchedule(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduleInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deleteScheduleInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteScheduleInSession")
    @ResponseWrapper(localName = "deleteScheduleInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeleteScheduleInSessionResponse")
    public boolean deleteScheduleInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "resumeScheduleReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "resumeSchedule", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResumeSchedule")
    @ResponseWrapper(localName = "resumeScheduleResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResumeScheduleResponse")
    public boolean resumeSchedule(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "resumeScheduleInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "resumeScheduleInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResumeScheduleInSession")
    @ResponseWrapper(localName = "resumeScheduleInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.ResumeScheduleInSessionResponse")
    public boolean resumeScheduleInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "suspendScheduleReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "suspendSchedule", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.SuspendSchedule")
    @ResponseWrapper(localName = "suspendScheduleResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.SuspendScheduleResponse")
    public boolean suspendSchedule(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "suspendScheduleInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "suspendScheduleInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.SuspendScheduleInSession")
    @ResponseWrapper(localName = "suspendScheduleInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.SuspendScheduleInSessionResponse")
    public boolean suspendScheduleInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param jobInstanceID
     * @param userID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelScheduleReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "cancelSchedule", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.CancelSchedule")
    @ResponseWrapper(localName = "cancelScheduleResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.CancelScheduleResponse")
    public String cancelSchedule(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param jobInstanceID
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelScheduleInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "cancelScheduleInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.CancelScheduleInSession")
    @ResponseWrapper(localName = "cancelScheduleInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.CancelScheduleInSessionResponse")
    public String cancelScheduleInSession(
        @WebParam(name = "jobInstanceID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String jobInstanceID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param password
     * @param userID
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.DeliveryServiceDefinition
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getDeliveryServiceDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getDeliveryServiceDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDeliveryServiceDefinition")
    @ResponseWrapper(localName = "getDeliveryServiceDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDeliveryServiceDefinitionResponse")
    public DeliveryServiceDefinition getDeliveryServiceDefinition(
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.v2.DeliveryServiceDefinition
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getDeliveryServiceDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getDeliveryServiceDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDeliveryServiceDefinitionInSession")
    @ResponseWrapper(localName = "getDeliveryServiceDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.GetDeliveryServiceDefinitionInSessionResponse")
    public DeliveryServiceDefinition getDeliveryServiceDefinitionInSession(
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param password
     * @param deliveryRequest
     * @param userID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deliveryServiceReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deliveryService", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeliveryService")
    @ResponseWrapper(localName = "deliveryServiceResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeliveryServiceResponse")
    public String deliveryService(
        @WebParam(name = "deliveryRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        DeliveryRequest deliveryRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param deliveryRequest
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "deliveryServiceInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "deliveryServiceInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeliveryServiceInSession")
    @ResponseWrapper(localName = "deliveryServiceInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "com.oracle.xmlns.oxp.service.v2.DeliveryServiceInSessionResponse")
    public String deliveryServiceInSession(
        @WebParam(name = "deliveryRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        DeliveryRequest deliveryRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

}
