
package genericsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.ucm.Generic;
import com.oracle.ucm.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericSoapPortType", targetNamespace = "urn:GenericSoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericSoapPortType {


    /**
     * 
     * @param genericRequest
     * @return
     *     returns com.oracle.ucm.Generic
     */
    @WebMethod(operationName = "GenericSoapOperation", action = "urn:GenericSoap/GenericSoapOperation")
    @WebResult(name = "GenericResponse", targetNamespace = "http://www.oracle.com/UCM", partName = "GenericResponse")
    public Generic genericSoapOperation(
        @WebParam(name = "GenericRequest", targetNamespace = "http://www.oracle.com/UCM", partName = "GenericRequest")
        Generic genericRequest);

}
