
package genericsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenericSoapService", targetNamespace = "urn:GenericSoap", wsdlLocation = "https://edvn-test.fa.us2.oraclecloud.com/idcws/GenericSoapPort?wsdl")
public class GenericSoapService
    extends Service
{

    private final static URL GENERICSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERICSOAPSERVICE_EXCEPTION;
    private final static QName GENERICSOAPSERVICE_QNAME = new QName("urn:GenericSoap", "GenericSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://edvn-test.fa.us2.oraclecloud.com/idcws/GenericSoapPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICSOAPSERVICE_WSDL_LOCATION = url;
        GENERICSOAPSERVICE_EXCEPTION = e;
    }

    public GenericSoapService() {
        super(__getWsdlLocation(), GENERICSOAPSERVICE_QNAME);
    }

    public GenericSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICSOAPSERVICE_QNAME, features);
    }

    public GenericSoapService(URL wsdlLocation) {
        super(wsdlLocation, GENERICSOAPSERVICE_QNAME);
    }

    public GenericSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICSOAPSERVICE_QNAME, features);
    }

    public GenericSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericSoapPortType
     */
    @WebEndpoint(name = "GenericSoapPort")
    public GenericSoapPortType getGenericSoapPort() {
        return super.getPort(new QName("urn:GenericSoap", "GenericSoapPort"), GenericSoapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericSoapPortType
     */
    @WebEndpoint(name = "GenericSoapPort")
    public GenericSoapPortType getGenericSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:GenericSoap", "GenericSoapPort"), GenericSoapPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICSOAPSERVICE_EXCEPTION!= null) {
            throw GENERICSOAPSERVICE_EXCEPTION;
        }
        return GENERICSOAPSERVICE_WSDL_LOCATION;
    }

}
